# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**\*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  releaseProject: '$(Build.SourcesDirectory)\Honeywell.DataCollection\Honeywell.DataCollection.csproj'
  timestamp: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: projectversionasvariable@1
  inputs:
    path: '$(releaseProject)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'pack'
    arguments: >
      $(releaseProject)
      --output $(Build.ArtifactStagingDirectory)
      --no-build
      /p:Configuration=$(buildConfiguration)
      /p:PackageVersion=$(Version.MajorMinorBuild)-preview-$(timestamp)
      /p:PackageId=DevFromDownUnder.Honeywell.DataCollection

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Honeywell.DataCollection/Honeywell.DataCollection-nuget-preview'
